version: "3"

services:
  app:
    build: .
    image: location_tree
    container_name: location_tree_app
    restart: always
    environment:
      STAGE: debug
      NEO4J_BOLT_URL: bolt://neo4j:location_tree_pwd@neo:7687
    ports:
      - "8000:8000"
    volumes:
      - ./location_tree:/app
    depends_on:
      - neo
    networks:
      - location_tree_network
    command: python manage.py runserver 0.0.0.0:8000

  neo:
    image: neo4j:3.5.5
    container_name: location_tree_database
    restart: always
    environment:
      NEO4J_AUTH: neo4j/location_tree_pwd
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ~/data/location_tree/neo4j:/data
    networks:
      - location_tree_network

networks:
  location_tree_network:
    driver: bridge
